version: '3'

services:
  postgresql:
    restart: always
    image: postgres:11
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: goSp0rt
      POSTGRES_USER: postgres
    volumes:
      - ./data/db:/var/lib/postgresql

  site:
    build: .
    restart: always
    image: site:latest
    container_name: site
    expose:
      - 8000
    labels:
      - "traefik.backend=site"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:letsport.cf"
      - "traefik.enable=true"
    networks:
      - traefik
    volumes:
      - ./data/letsport:/letsport:rw

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - "IP:80:80"
      - "IP:443:443"
    container_name: traefik
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/ssl/traefik.toml:/traefik.toml
      - ./data/ssl/acme.json:/acme.json
    container_name: traefik

networks:
  traefik:
    external: true
